// Generated by gencpp from file flora_msgs/FloraMsg.msg
// DO NOT EDIT!


#ifndef FLORA_MSGS_MESSAGE_FLORAMSG_H
#define FLORA_MSGS_MESSAGE_FLORAMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flora_msgs
{
template <class ContainerAllocator>
struct FloraMsg_
{
  typedef FloraMsg_<ContainerAllocator> Type;

  FloraMsg_()
    : detail()
    , id(0)  {
    }
  FloraMsg_(const ContainerAllocator& _alloc)
    : detail(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detail_type;
  _detail_type detail;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::flora_msgs::FloraMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flora_msgs::FloraMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FloraMsg_

typedef ::flora_msgs::FloraMsg_<std::allocator<void> > FloraMsg;

typedef boost::shared_ptr< ::flora_msgs::FloraMsg > FloraMsgPtr;
typedef boost::shared_ptr< ::flora_msgs::FloraMsg const> FloraMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flora_msgs::FloraMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flora_msgs::FloraMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flora_msgs::FloraMsg_<ContainerAllocator1> & lhs, const ::flora_msgs::FloraMsg_<ContainerAllocator2> & rhs)
{
  return lhs.detail == rhs.detail &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flora_msgs::FloraMsg_<ContainerAllocator1> & lhs, const ::flora_msgs::FloraMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flora_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flora_msgs::FloraMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flora_msgs::FloraMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flora_msgs::FloraMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flora_msgs::FloraMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flora_msgs::FloraMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flora_msgs::FloraMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flora_msgs::FloraMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f5528a9204f8b31c9206fc97a4a07bb";
  }

  static const char* value(const ::flora_msgs::FloraMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f5528a9204f8b31ULL;
  static const uint64_t static_value2 = 0xc9206fc97a4a07bbULL;
};

template<class ContainerAllocator>
struct DataType< ::flora_msgs::FloraMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flora_msgs/FloraMsg";
  }

  static const char* value(const ::flora_msgs::FloraMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flora_msgs::FloraMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string detail\n"
"int32 id\n"
;
  }

  static const char* value(const ::flora_msgs::FloraMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flora_msgs::FloraMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detail);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloraMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flora_msgs::FloraMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flora_msgs::FloraMsg_<ContainerAllocator>& v)
  {
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detail);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLORA_MSGS_MESSAGE_FLORAMSG_H
